// Code generated by go-swagger; DO NOT EDIT.

package api_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HandlersUpdateUserInput handlers update user input
//
// swagger:model handlers.UpdateUserInput
type HandlersUpdateUserInput struct {

	// current organization id
	CurrentOrganizationID string `json:"current_organization_id,omitempty"`

	// device token
	DeviceToken string `json:"device_token,omitempty"`

	// username
	Username string `json:"username,omitempty"`
}

// Validate validates this handlers update user input
func (m *HandlersUpdateUserInput) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this handlers update user input based on context it is used
func (m *HandlersUpdateUserInput) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HandlersUpdateUserInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HandlersUpdateUserInput) UnmarshalBinary(b []byte) error {
	var res HandlersUpdateUserInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
