// Code generated by go-swagger; DO NOT EDIT.

package api_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelsOrganization models organization
//
// swagger:model models.Organization
type ModelsOrganization struct {

	// description
	Description string `json:"description,omitempty"`

	// id
	// Example: aa22666c-0f57-45cb-a449-16efecc04f2e
	ID string `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this models organization
func (m *ModelsOrganization) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this models organization based on context it is used
func (m *ModelsOrganization) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModelsOrganization) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelsOrganization) UnmarshalBinary(b []byte) error {
	var res ModelsOrganization
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
