// Code generated by go-swagger; DO NOT EDIT.

package api_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelsUser models user
//
// swagger:model models.User
type ModelsUser struct {

	// auth id
	AuthID string `json:"auth_id,omitempty"`

	// current organization id
	CurrentOrganizationID string `json:"current_organization_id,omitempty"`

	// TODO: This should be in a separate table but for now we'll just store it here
	DeviceToken string `json:"device_token,omitempty"`

	// id
	// Example: aa22666c-0f57-45cb-a449-16efecc04f2e
	ID string `json:"id,omitempty"`

	// Organizations         []Organization `json:"organizations" gorm:"many2many:user_organizations;"`
	Username string `json:"username,omitempty"`
}

// Validate validates this models user
func (m *ModelsUser) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this models user based on context it is used
func (m *ModelsUser) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModelsUser) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelsUser) UnmarshalBinary(b []byte) error {
	var res ModelsUser
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
