// Code generated by go-swagger; DO NOT EDIT.

package api_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelsValidationError models validation error
//
// swagger:model models.ValidationError
type ModelsValidationError struct {

	// error
	// Example: something bad
	Error string `json:"error,omitempty"`

	// field
	Field string `json:"field,omitempty"`
}

// Validate validates this models validation error
func (m *ModelsValidationError) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this models validation error based on context it is used
func (m *ModelsValidationError) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModelsValidationError) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelsValidationError) UnmarshalBinary(b []byte) error {
	var res ModelsValidationError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
